/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Environment */

#ifndef _Included_Environment
#define _Included_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Environment
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Environment_setenv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Environment
 * Method:    unsetenv
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Environment_unsetenv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Environment
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Environment_getenv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Environment
 * Method:    isset
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Environment_isset
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
