// 
// Filename : CommandIds.java
//
// UK Crown Copyright (c) 2005. All Rights Reserved
//
package org.xtuml.masl.inspector.socketConnection.commands;

public enum ServerCommandId {
    GET_PROCESS_DATA, CATCH_CONSOLE, RUN_DOMAIN_SERVICE, RUN_TERMINATOR_SERVICE, RUN_OBJECT_SERVICE, FIRE_EVENT,
    SCHEDULE_EVENT, CANCEL_TIMER, TRACE_LINES, TRACE_BLOCKS, TRACE_EXCEPTIONS, TRACE_EVENTS, STEP_LINES, STEP_BLOCKS,
    STEP_EXCEPTIONS, STEP_EVENTS, ENABLE_TIMERS, CONTINUE_EXECUTION, PAUSE_EXECUTION, STEP_EXECUTION, SET_BREAKPOINT,
    GET_INSTANCE_DATA, GET_SELECTED_INSTANCE_DATA, GET_SINGLE_INSTANCE_DATA, GET_RELATED_INSTANCE_DATA, GET_EVENT_QUEUE,
    GET_TIMER_QUEUE, GET_LOCAL_VARIABLES, GET_STACK, GET_ASSIGNER_STATE, RUN_TEST_SCHEDULE, GET_INSTANCE_COUNT,
    CREATE_INSTANCE_POPULATION, CREATE_SINGLE_INSTANCE, UPDATE_SINGLE_INSTANCE, DELETE_SINGLE_INSTANCE,
    CREATE_RELATIONSHIPS, CREATE_SUPERSUBTYPES, INVOKE_PLUGIN_ACTION, GET_PLUGIN_FLAG, GET_PLUGIN_PROPERTY,
    SET_PLUGIN_FLAG, SET_PLUGIN_PROPERTY,
}
