version: '3.8'
name: xtuml-masl
volumes:
  ConanServer:
  ConanCache:

services:
  conan-server:
    build:
      context: conan-server
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - 9300:9300
    volumes:
      - type: volume
        source: ConanServer
        target: /conan-data

  command:
    build:
      context: masl-dev
    depends_on:
      - conan-server
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    profiles:
      - tools

