name: masl
volumes:
  ConanCache:

services:
  masl-dev:
    image: levistarrett/masl-dev:latest
    build:
      context: masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    profiles:
      - tools
      - all
