version: '3.8'
name: xtuml-masl
volumes:
  ConanServer:
  ConanCache:

services:
  conan-server:
    image: xtuml/conan-server
    build:
      context: conan-server
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - 9300:9300
    volumes:
      - type: volume
        source: ConanServer
        target: /conan-data

  masl-dev:
    image: xtuml/masl-dev
    build:
      context: masl-dev
    depends_on:
      - conan-server
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    profiles:
      - tools
      - all

  masl-run:
    image: xtuml/masl-run
    build:
      context: masl-run
    depends_on:
      - conan-server
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    profiles:
      - run

  masl-populate:
    image: xtuml/masl-populate
    build:
      context: ..
      dockerfile: docker/masl-populate/Dockerfile
    depends_on:
      - conan-server
    profiles:
      - populate
      - all

