# base image
FROM levistarrett/masl-base:v1

# expose default ports for inspector
EXPOSE 20000/tcp
EXPOSE 30000/tcp
EXPOSE 40000/tcp

# execute script
COPY docker/execute-masl.sh /usr/local/bin/execute-masl.sh
ENTRYPOINT ["/usr/local/bin/execute-masl.sh"]
