/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xtuml_masl_util_Math */

#ifndef _Included_org_xtuml_masl_util_Math
#define _Included_org_xtuml_masl_util_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xtuml_masl_util_Math
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_xtuml_masl_util_Math_sqrt
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
